### ISSUE TITLE
Finger print wrong

### ISSUE THREAD

**Issue by CHENPINGFIONA** [muhdfirdaus/NTUC-API#22]
https://github.com/muhdfirdaus/NTUC-API/blob/master/public_html/index.php#L80 
Correct format should be
 fingerprint was the result of applying SHA256 on the string “fc10bf07-3d34-49cd-a408-99a37bf804b7,a31704c1-edcd-41e1-bec3-de5907ab955f,1439321947,POST,/api/updates/,nric=S7xxxxxxH&amount=649.05&date=20150811&source=cruises”.

**Comment by parisqian-misa** [comment]
Please add the shared secret in. Otherwise, we would always get 401 error :joy:

**Comment by josergcatmisatravelcom** [comment]
I am trying to pull the changes to the ntuctest.misatravel.com server, but we have some DNS problems...

**Comment by josergcatmisatravelcom** [comment]
Server updated! let's test now
