### ISSUE TITLE
The generic fingerprint function

### ISSUE THREAD

**Issue by josergcatmisatravelcom** [muhdfirdaus/NTUC-API#25]
<pre>
function calculateFingerprint($apikey, $secret, $timestamp, $method, $resourceUri, $data){
        return hash('sha256', "$apikey,$secret,$timestamp,$method,$resourceUri,$data" );
}
</pre>

then you can rewrite your "fp" function as

<pre>
function fp($apikey, $secret, $timestamp, $nric, $amount, $date, $source, $method, $resourceUri){
        $fp = calculateFingerprint($apikey, $secret, $timestamp, $method, $resourceUri, "nric=".$nric."&amount=".$amount."&date=".$date."&source=".$source );
        return $fp;
}
</pre>

**Notes:** string format in PHP http://php.net/manual/en/language.types.string.php#language.types.string.parsing

<pre>
$juice = "apple";
echo "He drank some $juice juice.".PHP_EOL;
</pre>

outputs

<pre>
He drank some apple juice.
</pre>

;)

**Comment by parisqian-misa** [comment]
``` PHP
"nric=".$nric."&amount=".$amount."&date=".$date."&source=".$source
```

is equivalent to

``` PHP
"nric=$nric&amount=$amount&date=$date&source=$source"
```

To play safe, you can also try using `{` to wrap the variable up.
like this:

``` PHP
"nric={$nric}&amount={$amount}&date={$date}&source={$source}"
```

But most of the case, it would just be fine.

The reason of using this trick can be as simply as making you life easier, keep typing `.` & `"` sometimes could be very annoying. And it enhanced the readability as well. The readability and reusability are 2 very important factors of maintainability, or in another word code quality.

Let us be lazy coders :beers:
