### ISSUE TITLE
500 server error 

### ISSUE THREAD

**Issue by CHENPINGFIONA** [muhdfirdaus/NTUC-API#31]
# Status

500 Internal Server Error Show explanation Loading time: 25
# Request headers

fingerprint: 93400b22c9dc2d1b3edad590a43ee6cb8ef9078ca5908646dac8b8d3bf83538d
timestamp: 1442996948
Origin: chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo
apikey: xxxxxxxxxx
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Content-Type: application/x-www-form-urlencoded 
Accept: _/_
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6
# Response headers

Server: nginx/1.8.0 
Date: Fri, 02 Oct 2015 06:58:39 GMT 
Content-Type: text/html;charset=UTF-8 
Transfer-Encoding: chunked 
Connection: keep-alive
X-Powered-By: PHP/5.6.13
# Slim Application Error

The application could not run because of the following error:

Details

Type: ErrorException
Code: 8
Message: Undefined variable: apiKey
File: /home/ntuctest.misatravel.com/public_html/index.php
Line: 92
Trace
#0 /home/ntuctest.misatravel.com/public_html/index.php(92): Slim\Slim::handleErrors(8, 'Undefined varia...', '/home/ntuctest....', 92, Array)
#1 [internal function]: {closure}()
#2 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#3 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#4 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#5 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#6 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#7 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#8 /home/ntuctest.misatravel.com/public_html/index.php(175): Slim\Slim->run()
#9 {main}

**Comment by parisqian-misa** [comment]
https://github.com/muhdfirdaus/NTUC-API/blob/master/public_html/index.php#L69

The header is key-value pairs already, why are we converting it to arrays?

http://php.net/manual/en/language.types.array.php

If you want to grab all keys, you can use http://php.net/manual/en/function.array-keys.php function
And if you want to check if any key exist, for example, if apikey exist, you can use
http://php.net/manual/en/function.array-key-exists.php function, like 

``` php
# assuming $headers is the header values from the http request
if (array_key_exists('apikey', $headers)) { # just for example, in practice isset() / !empty() are even safer
    $apikey=$headers[‘apikey’];
}
```

**Comment by muhdfirdaus** [comment]
sorry for the error. We are currently testing the system. My friend Khairul, who are fixing the error can't test the system on his computer so we've decided to push to git before I pull and test on my computer. The error is not fixed yet. We're still configuring some issues. Thank you.

**Comment by parisqian-misa** [comment]
No problem, take your time.
I just double checked with my colleague, she told me that she may need to test the system before next Monday. So make sure we can have a functional release at least by this weekend. I would suggest to deploy the previous version first before you launching any new bugfix.
:dog: Thank you a lot :dog:

**Comment by muhdfirdaus** [comment]
I've already fix and run few test. So far it got no problem, I think. If there is any error please kindly tell me. I will try to fix it ASAP. :dancer:
